### ISSUE TITLE
How about a screenshot?

### ISSUE THREAD

**Issue by PySimpleGUI** [raziolo/PwdManager#1]
Can't help but notice the top of your readme:

![image](https://user-images.githubusercontent.com/46163555/104859773-8d8d1f80-58f5-11eb-85f7-306d87f9fad6.png)

mentions that you've not got a GUI.  That's exciting stuff!

I think visitors may enjoy seeing your GUI, either as a static image or perhaps a GIF file if you're feeling particularly ambitious.

The way I've done it a number of times is to cheat and put the image into a GitHub issue that I then reference in my readme.  It's quick and easy way to get images served up for free.  Here's a video on how to do it:

https://youtu.be/C4PVKW756fo

Congrats on the progress on your project!

**Comment by raziolo** [comment]
Hi @PySimpleGUI,
I'm so glad that the dev of one of the libraries I use in this project watched my code.
The same way I thank you for the tip I will get to work and add them as soon as possible.
I will close the issue when I add the screenschots/GIFs in the readme.md file

**Comment by raziolo** [comment]
Hi again, 
I added 2 screenshots both if the GUI and the CLI. The method you linked was very easy to use, thanks again.
I will add some GIFs too maybe!!
